
name: Build and Push Docker Images

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set repo name to lowercase
        id: vars
        run: |
          REPO_LOWER=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "repo=${REPO_LOWER}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./front-end
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.repo }}/frontend:latest

  build_and_push_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set repo name to lowercase
        id: vars
        run: |
          REPO_LOWER=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "repo=${REPO_LOWER}" >> $GITHUB_OUTPUT


      - name: Build and push backend-php image
        uses: docker/build-push-action@v3
        with:
          context: ./back-end
          file: ./back-end/dockerfiles/php.dockerfile
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.repo }}/backend-php:latest
          build-args: |
            UID=1001
            GID=1001
            USER=runner

      - name: Build and push backend-nginx image
        uses: docker/build-push-action@v3
        with:
          context: ./back-end
          file: ./back-end/dockerfiles/nginx.dockerfile
          push: true
          tags: ghcr.io/${{ steps.vars.outputs.repo }}/backend-nginx:latest
          build-args: |
            UID=1001
            GID=1001
            USER=runner
