
name: Build and Push Docker Images

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Prepare Docker Hub namespace
        id: dh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          USER_LOWER=$(echo "${DOCKERHUB_USERNAME}" | tr '[:upper:]' '[:lower:]')
          echo "ns=${USER_LOWER}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./front-end
          push: true
          tags: docker.io/${{ steps.dh.outputs.ns }}/azubi-frontend:latest

  build_and_push_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Verify Docker Hub secrets are present
        run: |
          if [ -z "${DOCKERHUB_USERNAME}" ]; then echo "Missing DOCKERHUB_USERNAME secret" && exit 1; fi
          if [ -z "${DOCKERHUB_PASSWORD}" ]; then echo "Missing DOCKERHUB_PASSWORD secret" && exit 1; fi
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Prepare Docker Hub namespace
        id: dh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          USER_LOWER=$(echo "${DOCKERHUB_USERNAME}" | tr '[:upper:]' '[:lower:]')
          echo "ns=${USER_LOWER}" >> $GITHUB_OUTPUT


      - name: Build and push backend-php image
        uses: docker/build-push-action@v3
        with:
          context: ./back-end
          file: ./back-end/dockerfiles/php.dockerfile
          push: true
          tags: docker.io/${{ steps.dh.outputs.ns }}/azubi-backend-php:latest
          build-args: |
            UID=1001
            GID=1001
            USER=runner

      - name: Build and push backend-nginx image
        uses: docker/build-push-action@v3
        with:
          context: ./back-end
          file: ./back-end/dockerfiles/nginx.dockerfile
          push: true
          tags: docker.io/${{ steps.dh.outputs.ns }}/azubi-backend-nginx:latest
          build-args: |
            UID=1001
            GID=1001
            USER=runner