
name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set repo name to lowercase
        id: string
        run: echo "repo=${{ github.repository }}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./front-end
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest

  build_and_push_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set repo name to lowercase
        id: string
        run: echo "repo=${{ github.repository }}" >> $GITHUB_OUTPUT


      - name: Build and push backend-php image
        uses: docker/build-push-action@v3
        with:
          context: ./back-end
          file: ./back-end/dockerfiles/php.dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/backend-php:latest

      - name: Build and push backend-nginx image
        uses: docker/build-push-action@v3
        with:
          context: ./back-end
          file: ./back-end/dockerfiles/nginx.dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/backend-nginx:latest
